name: Lasr-Llama31_8b-Debug
class_name: LasrSearcher
api_type: "vllm"
api_model: "meta-llama/Llama-3.1-8B-Instruct"
model_url: "http://localhost:{}/v1"

num_iterations: 5
num_populations: 3
llm_weight: 0.005
early_stopping_condition: null
max_num_samples: 2000