name: LasrHfinf
class_name: LasrSearcher
api_type: "hfinf"
api_model: "meta-llama/Llama-3.1-8B-Instruct"
model_url: "https://api-inference.huggingface.co/models/meta-llama/Llama-3.1-8B-Instruct/v1"

num_iterations: 25
num_populations: 10
llm_weight: 0.005
early_stopping_condition: null
max_num_samples: 2000