name: LlmsrDirect_Llama31-8b
class_name: LLMSRSearcher
api_type: "vllm"
api_model: "meta-llama/Llama-3.1-8B-Instruct"
api_url: "http://localhost:{}/v1"
global_max_sample_num: 1000
samples_per_prompt: 1000
num_islands: 1