name: LlmsrDirect_Llama31-8b
class_name: LLMSRSearcher
api_type: "openai"
api_model: "gpt-3.5-turbo-0125"
api_url: "https://api.openai.com/v1/"
global_max_sample_num: 1000
samples_per_prompt: 1000
num_islands: 1