name: LlmsrHfinf
class_name: LLMSRSearcher
api_type: "hfinf"
api_model: "meta-llama/Llama-3.1-8B-Instruct"
api_url: "https://api-inference.huggingface.co/models/meta-llama/Llama-3.1-8B-Instruct/"
global_max_sample_num: 1000
samples_per_prompt: 4
num_islands: 10